#!/bin/sh -exu
CHANNEL=$1

git submodule init ./Madek
cd ./Madek
git fetch
git submodule foreach --recursive 'git reset --hard HEAD'
git reset --hard "origin/${CHANNEL}"
git submodule update --recursive --force deploy
