---
madek_external_hostname: street.ars.is

# storage
setup_storage_directories: true
madek_storage_dir: /srv/madekdata
madek_file_storage_dir: /srv/madekdata/attachments
madek_thumbnail_storage_dir: /srv/madekdata/attachments
madek_tmp_dir: /srv/madekdata/tmp

# audio and videos previews
zencoder_enabled: false

# backups
# db_backups_enabled: False

# customize
madek_webapp_html_extra_head_end: |
  <link rel=stylesheet type=text/css href=/assets/local-theme.css>

madek_webapp_html_extra_head_start: |
  <!--
       __       __                  __            __
  /  \     /  |                /  |          /  |
  $$  \   /$$ |  ______    ____$$ |  ______  $$ |   __
  $$$  \ /$$$ | /      \  /    $$ | /      \ $$ |  /  |
  $$$$  /$$$$ | $$$$$$  |/$$$$$$$ |/$$$$$$  |$$ |_/$$/
  $$ $$ $$/$$ | /    $$ |$$ |  $$ |$$    $$ |$$   $$<
  $$ |$$$/ $$ |/$$$$$$$ |$$ \__$$ |$$$$$$$$/ $$$$$$  \
  $$ | $/  $$ |$$    $$ |$$    $$ |$$       |$$ | $$  |
  $$/      $$/  $$$$$$$/  $$$$$$$/  $$$$$$$/ $$/   $$/

  -->
